name = "gabrielfsdev"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MY_KV"
id = "preview"
preview_id = "preview"

[[d1_databases]]
binding = "DB"
database_name = "gabrielfs-db"
database_id = "local-db"
preview_database_id = "local-db"

[[r2_buckets]]
binding = "R2"
bucket_name = "gabrielfs-hero"
preview_bucket_name = "gabrielfs-hero-preview"
